// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  homepage_hero: defineAsyncComponent(() => import("./HomepageHero/index.vue")),
});
